inventory/urls.py
from inventory.views import *
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from django_filters.views import FilterView

urlpatterns = (
    
    url(r'^index', login_required(first_view.as_view()), name="index"),
    
    #url(r'^vertroncales', login_required(ver_troncales.as_view()), name="vertroncales"),
    
    url(r'^detalletroncal', login_required(trunk_info.as_view()), name="detalletroncal"),
    url(r'^detalletrunk', login_required(trunk_enla.as_view()), name="detalletrunk"),
    url(r'^detallenum', login_required(enla_dnis.as_view()), name="detallenum"),
    url(r'^detallednis', login_required(dnis_liext.as_view()), name="detallednis"),

    url(r'^registroncal', login_required(regis_troncal.as_view()), name="registroncal"),
    url(r'^(?P<pk>\d+)/editroncal', login_required(edit_troncal.as_view()), name="editroncal"),
    url(r'^elimtroncal/(?P<pk>\d+)', login_required(elim_troncal.as_view()), name='elimtroncal'),
    url(r'^addtroncal', login_required(addtrunk.as_view()), name='addtroncal'),
    
    url(r'^registroncal', login_required(regis_troncal.as_view()), name='registroncal'),
    url(r'^trunkenlacelist', login_required(trunkenlacelist.as_view()), name='trunkenlacelist'),

    url(r'^addusuario', login_required(addusuario.as_view()), name='addusuario'),
    url(r'^usuariolist', login_required(usuariolist.as_view()), name='usuariolist'),
    url(r'^usuarioeact/(?P<pk>\d+)$', login_required(usuarioeact.as_view()), name='usuarioeact'),
    url(r'^usuarioelim/(?P<pk>\d+)$', login_required(usuarioelim.as_view()), name='usuarioelim'),

    url(r'^trunkelist', login_required(trunkelist.as_view()), name='trunkelist'),
    url(r'^trunkeact/(?P<pk>\d+)$', login_required(trunkeact.as_view()), name='trunkeact'),
    url(r'^trunkelim/(?P<pk>\d+)$', login_required(trunkelim.as_view()), name='trunkelim'),
    url(r'^trunkdeta/(?P<pk>\d+)', login_required(trunkdeta.as_view()), name='trunkdeta'),

    url(r'^addlinea', login_required(addlinea.as_view()), name='addlinea'),
    url(r'^linealist', linealist.as_view(), name='linealist'),
    url(r'^lineaeact/(?P<pk>\d+)$', login_required(lineaeact.as_view()), name='lineaeact'),
    url(r'^lineaelim/(?P<pk>\d+)$', login_required(lineaelim.as_view()), name='lineaelim'),
    url(r'^lineadeta/(?P<pk>\d+)', login_required(lineadeta.as_view()), name='lineadeta'),
    
    url(r'^adddnis', login_required(adddnis.as_view()), name='adddnis'),
    url(r'^dnisaddcliente', login_required(addclientednis.as_view()), name='dnisaddcliente'),
    url(r'^dnislist', login_required(dnislist.as_view()), name='dnislist'),
    url(r'^dniseact/(?P<pk>\d+)$', login_required(dniseact.as_view()), name='dniseact'),
    url(r'^dniselim/(?P<pk>\d+)$', login_required(dniselim.as_view()), name='dniselim'),
    url(r'^dnisdeta/(?P<pk>\d+)', login_required(dnisdeta.as_view()), name='dnisdeta'),

    url(r'^addliext', login_required(addliext.as_view()), name='addliext'),
    url(r'^linextlist', login_required(linextlist.as_view()), name='linextlist'),
    url(r'^linexteact/(?P<pk>\d+)$', login_required(linexteact.as_view()), name='linexteact'),
    url(r'^linextelim/(?P<pk>\d+)$', login_required(linextelim.as_view()), name='linextelim'),
    url(r'^linextdeta/(?P<pk>\d+)', login_required(linextdeta.as_view()), name='linextdeta'),
    
    url(r'^addtiptrunk', login_required(addtiptrunk.as_view()), name='addtiptrunk'),
    url(r'^tiptrunklist', login_required(tiptrunklist.as_view()), name='tiptrunklist'),
    url(r'^tiptrunkeact/(?P<pk>\d+)$', login_required(tiptrunkeact.as_view()), name='tiptrunkeact'),
    url(r'^tiptrunkelim/(?P<pk>\d+)$', login_required(tiptrunkelim.as_view()), name='tiptrunkelim'),
    url(r'^tiptrunkdeta/(?P<pk>\d+)', login_required(tiptrunkdeta.as_view()), name='tiptrunkdeta'),

    url(r'^addcliente', login_required(addcliente.as_view()), name='addcliente'),
    url(r'^clienlist', login_required(clienlist.as_view()), name='clienlist'),
    url(r'^clieneact/(?P<pk>\d+)$', login_required(clieneact.as_view()), name='clieneact'),
    url(r'^clienelim/(?P<pk>\d+)$', login_required(clienelim.as_view()), name='clienelim'),
    url(r'^cliendeta/(?P<pk>\d+)', login_required(cliendeta.as_view()), name='cliendeta'),

    url(r'^addsede', login_required(addsede.as_view()), name='addsede'),
    url(r'^sedelist', login_required(sedelist.as_view()), name='sedelist'),
    url(r'^sedeeact/(?P<pk>\d+)$', login_required(sedeeact.as_view()), name='sedeeact'),
    url(r'^sedeelim/(?P<pk>\d+)$', login_required(sedeelim.as_view()), name='sedeelim'),
    url(r'^sededeta/(?P<pk>\d+)', login_required(sededeta.as_view()), name='sededeta'),

    url(r'^addciudad', login_required(addciudad.as_view()), name='addciudad'),
    url(r'^ciudadlist', login_required(ciudadlist.as_view()), name='ciudadlist'),
    url(r'^ciudadeact/(?P<pk>\d+)$', login_required(ciudadeact.as_view()), name='ciudadeact'),
    url(r'^ciudadelim/(?P<pk>\d+)$', login_required(ciudadelim.as_view()), name='ciudadelim'),
    url(r'^ciudaddeta/(?P<pk>\d+)', login_required(ciudaddeta.as_view()), name='ciudaddeta'),

    url(r'^addplataforma', login_required(addplataforma.as_view()), name='addplataforma'),
    url(r'^plataforlist', login_required(plataforlist.as_view()), name='plataforlist'),
    url(r'^plataforeact/(?P<pk>\d+)$', login_required(plataforeact.as_view()), name='plataforeact'),
    url(r'^plataforelim/(?P<pk>\d+)$', login_required(plataforelim.as_view()), name='plataforelim'),
    url(r'^platafordeta/(?P<pk>\d+)', login_required(platafordeta.as_view()), name='platafordeta'),

    url(r'^addcontrato', login_required(addcontrato.as_view()), name='addcontrato'),
    url(r'^contratolist', login_required(contratolist.as_view()), name='contratolist'),
    url(r'^contratoeact/(?P<pk>\d+)$', login_required(contratoeact.as_view()), name='contratoeact'),
    url(r'^contratoelim/(?P<pk>\d+)$', login_required(contratoelim.as_view()), name='contratoelim'),
    url(r'^contratodeta/(?P<pk>\d+)', login_required(contratodeta.as_view()), name='contratodeta'),

    url(r'^liexaddcliente', login_required(addclienteliex.as_view()), name='liexaddcliente'),
    url(r'^clienteliexlist', login_required(clienteliexlist.as_view()), name='clienteliexlist'),
    url(r'^clienteliexeact/(?P<pk>\d+)$', login_required(clienteliexeact.as_view()), name='clienteliexeact'),
    url(r'^clienteliexelim/(?P<pk>\d+)$', login_required(clienteliexelim.as_view()), name='clienteliexelim'),
    url(r'^clienteliexdeta/(?P<pk>\d+)', login_required(clienteliexdeta.as_view()), name='clienteliexdeta'),

    url(r'^addcodsalida', login_required(addcodsalida.as_view()), name='addcodsalida'),
    url(r'^codsalidalist', login_required(codsalidalist.as_view()), name='codsalidalist'),
    url(r'^codsalidaeact/(?P<pk>\d+)$', login_required(codsalidaeact.as_view()), name='codsalidaeact'),
    url(r'^codsalidaelim/(?P<pk>\d+)$', login_required(codsalidaelim.as_view()), name='codsalidaelim'),
    url(r'^codsalidadeta/(?P<pk>\d+)', login_required(codsalidadeta.as_view()), name='codsalidadeta'),

    url(r'^addpresalida', login_required(addpresalida.as_view()), name='addpresalida'),
    url(r'^presalidalist', login_required(presalidalist.as_view()), name='presalidalist'),
    url(r'^presalidaeact/(?P<pk>\d+)$', login_required(presalidaeact.as_view()), name='presalidaeact'),
    url(r'^presalidaelim/(?P<pk>\d+)$', login_required(presalidaelim.as_view()), name='presalidaelim'),
    url(r'^presalidadeta/(?P<pk>\d+)', login_required(presalidadeta.as_view()), name='presalidadeta'),

    url(r'^close', login_required(close.as_view()), name='close'),

     )

login/urls.py
from django.conf.urls import url
from login.views import *


urlpatterns = [
    url(r'^$', Viewlogin.as_view(), name="login"),
    url(r'^login', Viewlogin.as_view(), name="login"),
    url(r'^logout', Logout.as_view(),  name="logout"), 
]

machform/urls.py
import debug_toolbar
from django.conf import settings
from django.contrib import admin
from inventory.views import first_view
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
    
    url(r'^admin/', include(admin.site.urls)),


    url(r'^', include('login.urls', namespace='login', app_name='login')),
    url(r'^login/', include('login.urls', namespace='login', app_name='login')),


    url(r'^machform/', include('inventory.urls', namespace='inventory', app_name='inventory')),
    

    url(r'^reset/password', auth_views.password_reset, {'template_name':'registration/password_reset_form.html',
        'email_template_name':'registration/password_reset_email.html'}, name='password_reset'),
    url(r'^reset/password/done', auth_views.password_reset_done, {'template_name':'registration/password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/', auth_views.password_reset_confirm, {'template_name':'registration/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset/done', auth_views.password_reset_complete, {'template_name':'registration/password_reset_complete.html'}, name='password_reset_complete'),


]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

inventory/models.py
from django.db import models
from src.model import BaseModel
from django.utils import timezone
from django.contrib.auth.models import Group

#Plataforma
class plataform(BaseModel):
    name_plataform = models.CharField('Nombre Plataforma ', max_length=50, unique=True )

    def __str__(self):
    	return '%s' % (self.name_plataform)

    class Meta:
    	verbose_name_plural = 'Plataformas'
    	verbose_name = 'Plataforma'

#Clientes
class client(BaseModel):
    nom_client = models.CharField('Nombre cliente ',max_length=50, unique=True  )
      

    def __str__(self):
        return '%s' % (self.nom_client)

    class Meta:
        verbose_name_plural = 'Clientes'
        verbose_name = 'Cliente'

#Ciudad
class city(BaseModel):
    name_city = models.CharField('Nombre Ciudad ', max_length=50, unique=True)

    def __str__(self):
    	return '%s' % (self.name_city)

    class Meta:
    	verbose_name_plural = 'Ciudades'
    	verbose_name = 'Ciudad'
#Sede
class seat(BaseModel):
    name_seat = models.CharField('Nombre Sede ', max_length=50, unique=True)
    name_city = models.ForeignKey(city, verbose_name='Ciudad ')

    def __str__(self):
    	return '%s' % (self.name_seat)

    class Meta:
    	verbose_name_plural = 'Sedes'
    	verbose_name = 'Sede'
#Contrato
class contract(BaseModel):
    num_contract = models.CharField('Número contrato ', unique=True, max_length=255 )
    name_contract = models.CharField('Nombre contrato ', max_length=50)
    obser_contract = models.TextField('Observación ', max_length=100,blank=True)
    

    def __str__(self):
    	return '%s' % (self.num_contract)

    class Meta:
    	verbose_name_plural = 'Contratos'
    	verbose_name = 'Contrato'
#Tipo Troncal
class typetrunk(BaseModel):
    type_trunk = models.CharField('Tipo Troncal ', max_length=50, unique=True)
      

    def __str__(self):
    	return '%s' % (self.type_trunk)

    class Meta:
    	verbose_name_plural = 'Tipos de troncales'
    	verbose_name = 'Tipo de troncal'

#Codigo de salida
class codexit(BaseModel):
    CORE = (
            (1,'1'),
            (2,'2'),
            (3,'3'),
            (4,'4')
    )
    num_code = models.IntegerField('Código de salida ', unique=True)
    code_clie = models.ForeignKey(client, verbose_name='Nombre cliente ' )
    core = models.IntegerField('Core', choices=CORE )
    obser_codexit = models.TextField('Observación ', max_length=100,blank=True)
    

    def __str__(self):
    	return '%s' % (self.num_code)

    class Meta:
        verbose_name_plural = 'Códigos de salida'
        verbose_name = 'Código de salida'
        ordering = ['num_code']


#Prefijo de salida
class preexit(BaseModel):
    num_pref = models.IntegerField('Prefijo de salida ', unique=True)
    pref_clie = models.ForeignKey(client, verbose_name='Nombre cliente ')
    obser_preexit = models.TextField('Observación ', max_length=100, blank=True)
    

    def __str__(self):
    	return '%s' % (self.num_pref)

    class Meta:
        ordering = ['num_pref']
        verbose_name_plural = 'Prefijos de salida'
        verbose_name = 'Prefijo de salida'


#Linea externa
class linext(BaseModel):
    num_linext = models.CharField('Linea externa ', unique=True, max_length=255)
    num_prefx = models.ForeignKey(contract, verbose_name='Número de contrato ')  #Numero contrato
    nom_clie = models.ForeignKey(client, verbose_name='Cliente ')
    obser_linext= models.TextField('Observación ', max_length=100, blank=True)
    

    def __str__(self):
        return '%s' % (self.num_linext)

    class Meta:
        verbose_name_plural = 'Lineas externas'
        verbose_name = 'Linea externa'
        ordering = ['num_linext']

#DNIS
class dnis(BaseModel):
    num_dnis = models.CharField('DNIS ', unique=True, max_length=255)
    nom_clie = models.ForeignKey(client, verbose_name='Cliente ')
    num_des = models.CharField('Número de desborde ', blank=True, null=True, max_length=255) #número de desborde
    obser_dnis = models.TextField('Observación ', max_length=100, blank=True)
    

    def __str__(self):
        return '%s' % (self.num_dnis)

    class Meta:
        verbose_name_plural = 'DNIS'
        verbose_name = 'DNIS'
        ordering = ['num_dnis']


#Enlace
class enlace(BaseModel):

    PROPIETARIO = (
            ('Emtelco','Emtelco'),
            ('Cliente','Cliente')
    )
    enla_num = models.CharField('Número de linea ', max_length=50,  unique=True)
    enla_pro = models.CharField('Propietario linea', choices=PROPIETARIO, max_length=50)
    enla_clien = models.ForeignKey(client, verbose_name='Cliente ' ) #Clientes
    enla_sed = models.ForeignKey(seat, verbose_name='Sede ')  #Sede
    enla_plat = models.ForeignKey(plataform, verbose_name='Plataforma ' ) #plataforma
    enla_tartel = models.CharField('Tarjeta telefonica ',max_length=50 )#tarjeta telefonica
    enla_prov = models.CharField('Ubicación proveedor ',max_length=50, blank=True )#Ubicación proveedor
    enla_emt = models.CharField('Ubicación Emtelco ',max_length=50 )#Ubicación emtelco
    enla_obser= models.TextField('Observación ', max_length=100, blank=True)

    def __str__(self):
        return '%s' % (self.enla_num)

    class Meta:
        verbose_name_plural = 'Linea'
        verbose_name = 'Lineas'
        ordering = ['enla_num']

#Troncal
class trunk(BaseModel):
    num_trunk = models.CharField('Número troncal ', unique=True, max_length=250)
    type_trun = models.ForeignKey(typetrunk, verbose_name='Tipo de troncal ')
    #trunk_enla = models.ForeignKey(enlace, verbose_name='Enlace ' ) 
    obser_contract = models.TextField('Observación ', max_length=100, blank=True)
    

    def __str__(self):
        return '%s' % (self.num_trunk)

    class Meta:
        verbose_name_plural = 'Troncales'
        verbose_name = 'Troncal'
        ordering = ['num_trunk']


#enlace troncal-linea-dnis-externa
class trunkenlace(BaseModel):
    num_trunke = models.ForeignKey(trunk, verbose_name='Número troncal ')
    num_enlatr = models.ForeignKey(enlace, verbose_name='Número de linea ' )
    num_dnenla = models.ForeignKey(dnis, verbose_name='DNIS ')
    num_dnlin = models.ForeignKey(linext, verbose_name='Linea externa ' )
    obser = models.TextField('Observación', max_length=100, blank=True )    

    def __str__(self):
        return '%s' % (self.num_trunke)
        
    class Meta:
        verbose_name_plural = 'Enlaces'
        verbose_name = 'Enlace'
        ordering = ['num_trunke']

inventory/templates/inventory/city_confirm_delete.html
<html lang="es">
    <head>
        <title>Confirmar </title>
        <link rel="stylesheet" type="text/css" href="/static/admin/css/style.css">
        <link href="/static/admin/css/bootstrap.min.css" rel="stylesheet">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1"> 
        <meta name="robots" content="NONE,NOARCHIVE">
        <script src="/static/admin/js/jquery.js" type="text/javascript"></script>
        <script src="/static/admin/js/bootstrap.min.js"></script>
    </head>

    <body id="container">
    
        <script type="text/javascript">
        $( document ).ready(function() {
            $('.model-city').hide()
                
        });
        </script> 
       <div class="bg-home"></div>
        <header>
            <nav class="navbar navbar-default">
              <div class="container-fluid">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="{% url 'inventory:trunkenlacelist' %}"><img src="/static/admin/images/logo-emtelco.png" alt=""></a>
                </div>

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                  <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'login:logout' %}">Cerrar Sesión</a></li>
                    <li><a href="{% url 'inventory:presalidalist' %}">Prefijos de Salida</a></li>
                    <li><a href="{% url 'inventory:codsalidalist' %}">Còdigos de Salida</a></li>
                    <li><a class="active" href="/machform/trunkenlacelist/">Troncales</a></li>
                    {% if user.is_active and user.is_staff and user.is_superuser %}
                    <li><a  href="{% url 'inventory:usuariolist' %}">Usuarios</a></li>
                    {%endif%}
                     <li><a>Bienvenido <strong>{% firstof user.get_short_name user.get_username %}</strong>.</a></li>
                    
                  </ul>
                </div><!-- /.navbar-collapse -->
              </div><!-- /.container-fluid -->
            </nav>
            <div class="line shadow"></div>
        </header>

        <div class="alert-confirm">
             <form method="post">{% csrf_token %}
                <p align="center" >¿Estás seguro que deseas borrar la ciudad :  {{ object }} ?</p>

                <div class="row">
                    <div class="col-md-12">
                        <div class="col-md-6">
                            <a  type="submit" class="btn btn-back" href="{% url 'inventory:ciudadlist' %}">
                                Cancelar
                            </a>
                        </div>
                        <div class="col-md-6">
                            <button class="form-control" type="submit" value="Aceptar">Aceptar</button>
                        </div>
                    </div>
                </div>
                
            </form>
        </div>

        <footer>
            <div class="line"></div>
            <div class="footer">
                Copyright © 2018 Medellín | Colombia | Gerencia de Ingeniería y Desarrollo Emtelco S.A.S
            </div>
        </footer>
    </body>
</html>

inventory/templates/inventory/trunkenlace_form.html
<html lang="es">
    <head>
        <title>Registrar enlaces</title>
        <link rel="stylesheet" type="text/css" href="/static/admin/css/style.css">
        <link href="/static/admin/css/bootstrap.min.css" rel="stylesheet">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1"> 
        <meta name="robots" content="NONE,NOARCHIVE">
        <script src="/static/admin/js/jquery.js" type="text/javascript"></script>
        <script src="/static/admin/js/bootstrap.min.js"></script>
    </head>


    <body id="container">
    
        <script type="text/javascript">
        $( document ).ready(function() {
            $('.model-city').hide()
                
        });
        </script> 
       <div class="bg-home"></div>
        <header>
            <nav class="navbar navbar-default">
              <div class="container-fluid">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="{% url 'inventory:trunkenlacelist' %}"><img src="/static/admin/images/logo-emtelco.png" alt=""></a>
                </div>

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                  <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'login:logout' %}">Cerrar Sesión</a></li>
                    <li><a href="{% url 'inventory:presalidalist' %}">Prefijos de Salida</a></li>
                    <li><a href="{% url 'inventory:codsalidalist' %}">Còdigos de Salida</a></li>
                    <li><a class="active" href="/machform/trunkenlacelist/">Troncales</a></li>
                    {% if user.is_active and user.is_staff and user.is_superuser %}
                    <li><a  href="{% url 'inventory:usuariolist' %}">Usuarios</a></li>
                    {%endif%}
                     <li><a>Bienvenido <strong>{% firstof user.get_short_name user.get_username %}</strong>.</a></li>
                    
                  </ul>
                </div><!-- /.navbar-collapse -->
              </div><!-- /.container-fluid -->
            </nav>
            <div class="line shadow"></div>
        </header>

        <div class="container" id="content-home">
            <div class="padding">
            <form method="post">
                    {% csrf_token %}

                     <br>
                    <div class="clearfix"></div>    
                    <div class="padding">            
                        <div class="form-user">
                             <div class="form-group  col-md-12">
                                <div class="col-md-3">
                                    <label class="control-label">{{form.num_trunke.label}}</label>
                                </div>
                                <div class="col-md-7">
                                     {{form.num_trunke}}
                                     <p style="color:red">{{form.num_trunke.errors}}</p>
                                </div>
                                <div class="col-md-1">
                                    <a id="trunk" class="addlink" ><span class="glyphicon glyphicon-plus"></a>
                                    <a href="{% url 'inventory:trunkelist' %}" class="changelink" target="_blank"><span class="glyphicon glyphicon-eye-open"></span></a>
                                </div>
                             </div>
                             <div class="form-group  col-md-12">
                                <div class="col-md-3">
                                    <label class="control-label">{{form.num_enlatr.label}}</label>
                                </div>
                                <div class="form-group col-md-7">
                                      {{form.num_enlatr}}
                                      <p style="color:red">{{form.num_enlatr.errors}}</p>
                                </div>
                                <div class="form-group col-md-1">
                                    <a id="enla" class="addlink" ><span class="glyphicon glyphicon-plus"></a>
                                    <a href="{% url 'inventory:linealist' %}" class="changelink" target="_blank"><span class="glyphicon glyphicon-eye-open"></span></a>
                                </div>
                             </div>
                             <hr>
                             <div class="clearfix"></div>
                             <div class="margin"></div>
                            <div class="form-group  col-md-12">
                                <div class="col-md-3">
                                     <label class="control-label">{{form.num_dnenla.label}}</label>
                                </div>
                                <div class="col-md-7">
                                      {{form.num_dnenla}}
                                      <p style="color:red">{{form.num_dnenla.errors}}</p>
                                </div>
                                <div class="col-md-1">
                                    <a id="dnis" class="addlink" ><span class="glyphicon glyphicon-plus"></a>
                                    <a href="{% url 'inventory:dnislist' %}" class="changelink" target="_blank"><span class="glyphicon glyphicon-eye-open"></span></a>
                                </div>
                             </div>
                             <div class="form-group  col-md-12">
                                <div class="col-md-3">
                                     <label class="control-label">{{form.num_dnlin.label}}</label>
                                </div>
                                <div class="col-md-7">
                                     {{form.num_dnlin}}
                                     <p style="color:red">{{form.num_dnlin.errors}}</p>
                                </div>
                                 <div class="col-md-1">
                                    <a id="liext"  class="addlink" ><span class="glyphicon glyphicon-plus"></a>
                                    <a href="{% url 'inventory:linextlist' %}" class="changelink" target="_blank"><span class="glyphicon glyphicon-eye-open"></span></a>
                                </div>
                             </div>
                             <hr>
                             <div class="clearfix"></div>
                             <div class="margin"></div>
                             <div class="form-group col-md-12">
                                <div class="col-md-3">
                                     <label class="control-label">{{form.obser.label}}</label>
                                </div>
                                <div class="col-md-9">
                                     {{form.obser}}
                                     <p style="color:red">{{form.obser.errors}}</p>
                                </div>
                                <br>
                                <br>
                                <br>
                             </div>
                             
                             
                             <div class="clearfix"></div>
                             
                             <div class="col-md-4"></div>
                            <div class="form-group  col-md-12">
                                <div class="col-md-6">
                                     <a class="btn btn-back" href="{% url 'inventory:trunkenlacelist' %}">Atras</a>
                                </div>
                                <div class="col-md-6">
                                    <button class="form-control" type="submit" value="Agregar">Añadir</button>
                                </div>
                            </div>
                       </div>
                </div>



                </form>
                </div>
        </div>

        <footer>
            <div class="line"></div>
            <div class="footer">
                Copyright © 2018 Medellín | Colombia | Gerencia de Ingeniería y Desarrollo Emtelco S.A.S
            </div>
        </footer>
    </body>

  <script type="text/javascript">

  if (localStorage["idRegistroT"]) {
      jQuery('#id_num_trunke').val(localStorage["idRegistroT"]);
    }

  $("#trunk").click(function(){
    window.open("{% url 'inventory:addtroncal' %}",  "ventana1", "width=1000,height=1000")

  });

</script>
<script type="text/javascript">
  if (localStorage["idRegistroE"]) {
      jQuery('#id_num_enlatr').val(localStorage["idRegistroE"]);
    }
  
  $("#enla").click(function(){
    window.open("{% url 'inventory:addlinea' %} ",  "ventana1", "width=1000,height=1000")

  });
</script>
<script type="text/javascript">
  if (localStorage["idRegistroD"]) {
      jQuery('#id_num_dnenla').val(localStorage["idRegistroD"]);
    }
  
  $("#dnis").click(function(){
    window.open("{% url 'inventory:adddnis' %}",  "ventana1", "width=1000,height=1000")

  });
</script>
<script type="text/javascript">
  if (localStorage["idRegistroL"]) {
      jQuery('#id_num_dnlin').val(localStorage["idRegistroL"]);
    }
  
  $("#liext").click(function(){
    window.open("{% url 'inventory:addliext' %}",  "ventana1", "width=1000,height=1000")

  });
</script>
</html>